[[redirects]]
from = "https://jkjitendra.in/*"
to = "https://www.jkjitendra.in/:splat"
status = 301
force = true

[[redirects]]
from = "http://jkjitendra.in/*"
to = "https://www.jkjitendra.in/:splat"
status = 301
force = true


